name: Linux build (bash)

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        

      - name: Configure with CMake
        run: |
          git clone https://github.com/ValveSoftware/GameNetworkingSockets.git
        shell: bash

      - name: Install dependencies
        run: |
          sudo apt install libssl-dev
          sudo apt install libprotobuf-dev protobuf-compiler
        shell: bash

      - name: Configure with CMake
        run: |
          cd GameNetworkingSockets
          mkdir build
          cd build
          cmake -G Ninja .. -DBUILD_EXAMPLES=ON -DBUILD_TESTS=ON -DUSE_STEAMWEBRTC=ON
          ninja
        shell: bash
