name: Linux build

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: true
        type: string

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure with CMake
        shell: bash
        run: |
          git clone https://github.com/ValveSoftware/GameNetworkingSockets.git

      - name: Install dependencies
        shell: bash
        run: |
          sudo apt install libssl-dev
          sudo apt install libprotobuf-dev protobuf-compiler

      - name: Configure with CMake
        shell: bash
        run: |
          cd GameNetworkingSockets
          mkdir build
          cd build
          cmake -G Ninja .. -DBUILD_EXAMPLES=ON -DBUILD_TESTS=ON -DUSE_STEAMWEBRTC=ON
          ninja

      - name: Copy Release Files
        shell: bash
        run: |
          curDir=$PWD
          mkdir -p release
          cd release
          mkdir include
          mkdir lib

          cp -a "$curDir/GameNetworkingSockets/include/" "."
          find "$curDir/GameNetworkingSockets/build/src" -type f \( -name '*.a' -o -name '*.so' \) -print0 | xargs -0 -I{} cp {} lib/
          find "$curDir/GameNetworkingSockets/build/bin" -type f \( -name '*.a' -o -name '*.so' \) -print0 | xargs -0 -I{} cp {} lib/

      - name: Release Binaries
        uses: Silverlan/common_actions/release_nightly_binaries@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit: ${{ github.ref_name }}
          tag: "${{ github.event.inputs.tag }}"
