name: Linux build (bash)

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        

      - name: Configure with CMake
        run: |
          git clone https://github.com/ValveSoftware/GameNetworkingSockets.git
        shell: bash

      - name: Install dependencies
        run: |
          sudo apt install libssl-dev
          sudo apt install libprotobuf-dev protobuf-compiler
        shell: bash

      - name: Configure with CMake
        run: |
          cd GameNetworkingSockets
          mkdir build
          cd build
          cmake -G Ninja .. -DBUILD_EXAMPLES=ON -DBUILD_TESTS=ON -DUSE_STEAMWEBRTC=ON
          ninja
        shell: bash

      - name: Copy Release Files
        shell: bash
        run: |
          curDir=$PWD
          mkdir -p release
          cd release
          mkdir include
          mkdir lib

          cp -a "$curDir/GameNetworkingSockets/include/" "include/"
          find "$curDir/GameNetworkingSockets/build/src" -type f \( -name '*.a' -o -name '*.so' \) -print0 | xargs -0 -I{} cp {} lib/
          find "$curDir/GameNetworkingSockets/build/bin" -type f \( -name '*.a' -o -name '*.so' \) -print0 | xargs -0 -I{} cp {} lib/

      - name: Release Binaries
        uses: Silverlan/common_actions/release_nightly_binaries@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit: ${{ github.ref_name }}
          tag: 'test'
